@sahibinden_project_HostAddress = http://localhost:8000

### Kullanıcı Kaydı için POST İsteği

POST {{sahibinden_project_HostAddress}}/user/register
Content-Type: application/json

{
  "username": "tugcetascilar",
  "password": "12345",
  "email": "email.com",
  "name": "tugce",
  "surname": "tascilar",
  "phoneNumber": "1234567890"
}
