@sahibinden_project_HostAddress = http://localhost:8000


POST {{sahibinden_project_HostAddress}}/listing/saveproperty
Content-Type: application/json

{
    "Title": "Yeni Ev",
    "Description": "Merkeze yakın lüks ev",
    "Category": "emlak",
    "Price": 300000,
    "Date": "2021-06-01",
    "ImageFileName": "ev3.jpg",
    "M2": 97,
    "RoomCount": 2,
    "Age": 0,
    "Floor": 3,
    "HeatingType": "Kombi",
    "BuildingType": "Betonarme",
    "Location": "Ankara",
    "Status": "Satılık"  
}
