@sahibinden_project_HostAddress = http://localhost:8000


POST {{sahibinden_project_HostAddress}}/listing/saveproperty
Content-Type: application/json

{
    "Title": "Öğrenciden Pis Ev",
    "Description": "Merkeze Uzak Öğrenci evi",
    "Category": "Emlak",
    "Price": 200000,
    "Date": "2021-06-01",
    "ImageFileName": "ev2.jpg",
    "M2": 10,
    "RoomCount": 1,
    "Age": 50,
    "Floor": -3,
    "HeatingType": "Sobalı",
    "BuildingType": "Kumdan",
    "Location": "İstanbul/Silivri",
    "Status": "Kiralık"  
}
