# For more info on HTTP files go to https://aka.ms/vs/httpfile
@sahibinden_project_HostAddress = http://localhost:8000
@id=1

PUT {{sahibinden_project_HostAddress}}/listing/id/{{id}}
Content-Type: application/json

{
    "Category" : "Ev",
    "Title" : "deðiþtiredik",
    "Description" : "Bu bir put iþlemidir",
    "Price" : 10,
    "Date" : "2024.08.01",
    "ImageFileName" : "deneme.png"
}